// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProjectBusRouteGuider
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Microsoft.VisualStudio.TestPlatform.UnitTestFramework;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITest.Input;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WindowsRuntimeControls;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// AssertMethod1 - Use 'AssertMethod1ExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethod1()
        {
            #region Variable Declarations
            UITestControl uITake158GetdownatyourText = this.UIItemWindow.UIScrollerPane.UITake158GetdownatyourText;
            XamlEdit start = this.UICeylonBusRoutesWindow.UITextStartGroup.UITextBoxEdit;
            XamlEdit end = this.UICeylonBusRoutesWindow.UITextEndGroup.UITextBoxEdit;
            XamlButton search = this.UICeylonBusRoutesWindow.UIBestRoutesButton;

            start.Text = "Moratuwa";
            end.Text = "Piliyandala";
            Gesture.Tap(search);


                       
            #endregion



            // Verify that the 'ControlType' property of 'Take 158 . Get down at your destination, Piliyanda...' label equals 'Take 158. Get down at your destination, Piliyandala'
            Assert.AreEqual("Take 158. Get down at your destination, Piliyandala",  uITake158GetdownatyourText, "Wrong Value");
        }
        
        #region Properties
        public virtual AssertMethod1ExpectedValues AssertMethod1ExpectedValues
        {
            get
            {
                if ((this.mAssertMethod1ExpectedValues == null))
                {
                    this.mAssertMethod1ExpectedValues = new AssertMethod1ExpectedValues();
                }
                return this.mAssertMethod1ExpectedValues;
            }
        }
        
        public UICeylonBusRoutesWindow UICeylonBusRoutesWindow
        {
            get
            {
                if ((this.mUICeylonBusRoutesWindow == null))
                {
                    this.mUICeylonBusRoutesWindow = new UICeylonBusRoutesWindow();
                }
                return this.mUICeylonBusRoutesWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private AssertMethod1ExpectedValues mAssertMethod1ExpectedValues;
        
        private UICeylonBusRoutesWindow mUICeylonBusRoutesWindow;
        
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class AssertMethod1ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'ControlType' property of 'Take 158 . Get down at your destination, Piliyanda...' label equals 'Take 158. Get down at your destination, Piliyandala'
        /// </summary>
        public string UITake158GetdownatyourTextControlType = "Take 158. Get down at your destination, Piliyandala";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UICeylonBusRoutesWindow : XamlWindow
    {
        
        public UICeylonBusRoutesWindow()
        {
            #region Search Criteria
            this.SearchProperties[XamlControl.PropertyNames.Name] = "Ceylon Bus Routes";
            #endregion
        }
        
        #region Properties
        public UITextStartGroup UITextStartGroup
        {
            get
            {
                if ((this.mUITextStartGroup == null))
                {
                    this.mUITextStartGroup = new UITextStartGroup(this);
                }
                return this.mUITextStartGroup;
            }
        }
        
        public UITextEndGroup UITextEndGroup
        {
            get
            {
                if ((this.mUITextEndGroup == null))
                {
                    this.mUITextEndGroup = new UITextEndGroup(this);
                }
                return this.mUITextEndGroup;
            }
        }
        
        public XamlButton UIBestRoutesButton
        {
            get
            {
                if ((this.mUIBestRoutesButton == null))
                {
                    this.mUIBestRoutesButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUIBestRoutesButton.SearchProperties[XamlButton.PropertyNames.AutomationId] = "searchBestBtn";
                    #endregion
                }
                return this.mUIBestRoutesButton;
            }
        }
        #endregion
        
        #region Fields
        private UITextStartGroup mUITextStartGroup;
        
        private UITextEndGroup mUITextEndGroup;
        
        private XamlButton mUIBestRoutesButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UITextStartGroup : XamlControl
    {
        
        public UITextStartGroup(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Group";
            this.SearchProperties["AutomationId"] = "textStart";
            #endregion
        }
        
        #region Properties
        public XamlEdit UITextBoxEdit
        {
            get
            {
                if ((this.mUITextBoxEdit == null))
                {
                    this.mUITextBoxEdit = new XamlEdit(this);
                    #region Search Criteria
                    this.mUITextBoxEdit.SearchProperties[XamlEdit.PropertyNames.AutomationId] = "TextBox";
                    #endregion
                }
                return this.mUITextBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private XamlEdit mUITextBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UITextEndGroup : XamlControl
    {
        
        public UITextEndGroup(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Group";
            this.SearchProperties["AutomationId"] = "textEnd";
            #endregion
        }
        
        #region Properties
        public XamlEdit UITextBoxEdit
        {
            get
            {
                if ((this.mUITextBoxEdit == null))
                {
                    this.mUITextBoxEdit = new XamlEdit(this);
                    #region Search Criteria
                    this.mUITextBoxEdit.SearchProperties[XamlEdit.PropertyNames.AutomationId] = "TextBox";
                    #endregion
                }
                return this.mUITextBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private XamlEdit mUITextBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIItemWindow : UITestControl
    {
        
        public UIItemWindow()
        {
            #region Search Criteria
            this.TechnologyName = "UIA";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Window";
            this.SearchProperties["FrameworkId"] = "UIX";
            #endregion
        }
        
        #region Properties
        public UIScrollerPane UIScrollerPane
        {
            get
            {
                if ((this.mUIScrollerPane == null))
                {
                    this.mUIScrollerPane = new UIScrollerPane(this);
                }
                return this.mUIScrollerPane;
            }
        }
        #endregion
        
        #region Fields
        private UIScrollerPane mUIScrollerPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIScrollerPane : UITestControl
    {
        
        public UIScrollerPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.TechnologyName = "UIA";
            this.SearchProperties["FrameworkId"] = "UIX";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Pane";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = null;
            this.SearchProperties["AutomationId"] = "Scroller";
            #endregion
        }
        
        #region Properties
        public UITestControl UITake158GetdownatyourText
        {
            get
            {
                if ((this.mUITake158GetdownatyourText == null))
                {
                    this.mUITake158GetdownatyourText = new UITestControl(this);
                    #region Search Criteria
                    this.mUITake158GetdownatyourText.TechnologyName = "UIA";
                    this.mUITake158GetdownatyourText.SearchProperties["FrameworkId"] = "UIX";
                    this.mUITake158GetdownatyourText.SearchProperties[UITestControl.PropertyNames.ControlType] = "Text";
                    this.mUITake158GetdownatyourText.SearchProperties["AutomationId"] = "MessageBoxMessage";
                    #endregion
                }
                return this.mUITake158GetdownatyourText;
            }
        }
        #endregion
        
        #region Fields
        private UITestControl mUITake158GetdownatyourText;
        #endregion
    }
}
